### ISSUE TITLE
Quadrotor environment for RL with inner-loop controller

### ISSUE THREAD

**Issue by seong-hun** [fdcl-nrf/fym#44]
We need an environment to test that RL algorithms work well with inner-loop controller.

The environment may have
 - *obs*: observation state for an RL agent.
 - *action*: commands that would be entered into the inner-loop controller

 - [x] Reasonable dynamic model of quadrotor
 - [x] PID inner controller
 - [x] LQR inner controller, linearization module
 - [ ] Any ideas?
